---
- name: Create a secure user using Ansible Vault
  hosts: all
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Create user with encrypted password
      user:
        name: "{{ username }}"
        password: "{{ user_pass | password_hash('sha512') }}"
        state: present

    - name: Print confirmation
      debug:
        msg: "User {{ username }} created successfully with Vault password!"
