---
- name: package and service management
  hosts: all
  tasks:
    - name: remove httpd package
      yum:
        name: httpd
        state: absent
    - name: install httpd package
      yum:
        name: httpd
        state: present
    - name: start service
      service:
        name: httpd
        state: started
        enabled: yes

