---
- name: Propmt for input user
  hosts: all
  become: yes
  vars_prompt:
    - name: user_name
      prompt: Enter your name
      private: no
    - name: password
      prompt: Enter your password
      private: yes

  tasks:
    - name: create user with propmt
      user:
        name: "{{ user_name }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present

    - debug: 
        msg: "User {{ user_name }} has been created successfully!"
